---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-dotenv
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: hermes-dotenv
    template:
      engineVersion: v2
      data:
        .env: |
          TELEGRAM_BOT_TOKEN={{ .TELEGRAM_BOT_TOKEN }}
          TELEGRAM_ALLOWED_USERS={{ .TELEGRAM_ALLOWED_USERS }}
          API_SERVER_KEY={{ .API_SERVER_KEY }}
          HASS_TOKEN={{ .HASS_TOKEN }}
          HASS_URL={{ .HASS_URL }}
  dataFrom:
    - extract:
        key: hermes-dotenv
