---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifacts-caddyfile
data:
  Caddyfile: |
    :8080 {
      root * /srv/sites
      file_server browse
      header /*/ Cache-Control "no-cache"
      encode gzip
    }
