---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: print-library
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-slow
