apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
    namespace: default
stringData:
    config.toml: ENC[AES256_GCM,data:znWyRNk1ddifqtRJZ4aPOAzZNUNK90WLYJgSXvB1He6CKx2TgJLtBTEiPg+B7I1H2w+PkGdgDMptaOMFxDOzijSlvbY5/wt+z7p/rkVShkMXgQvXf1kb/8w/k2gnQhRAyO4eHl19qQHyInvFKIweE+jWHqJb3NtWrjTgV7CK2XxMjiQOWhl8dL/gAp+ZHAKam3yhKcOhGv/eqez/oj+pWEdPebBMqb1IoIdSNHbcZidRUn8DLECD9dBLZDazMbQRHg2bo+t+3zBFNLoblMY2h4Sr/FALpPdlaXWzD69ScZLLxOYDA1Z0cyliPUh+gqW8VZUz4UHX+g6CrObeHfldH5aG87GzmoqRTQyvGnuYB+27epq2dnKV7TTZ/QXL5CkSvA==,iv:h/RmBfMrbkwzlLDHqrv+Ugy/3wi+zmQgkbQz+H//kz8=,tag:8rYFW5Ged19ZzEEN8FozUw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNTBTZFBjMWIxYWtXUHZu
            SXZLNUZNWTQvVFUxUWY2VVdlZk1RaUIvZDNzCmpPby9LaDdyaGoxdFd6RDNyVzFS
            aTJvajRJQWNvN000WE4xQjB6YndVM00KLS0tIDhaNUFwT3NlZWhBTDhvbFVadDVE
            YmVGWnNwbzZFb0oveXhndUtWV1RmUjAKZOPILjmpRjjHNqTth+uQukzcFEbpdzwp
            3aT8fPvpfX8hRIOrAFwSYoAMescuIzGcO9Ch31IU2R8wp3I+zoOtEg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:47Z"
    mac: ENC[AES256_GCM,data:YFZhnanbi2DnAyYVU0jvsClXwYOSNC8+NCqxvHR0VIbyCHT+kQydOXwBLoexhfBqCojT0g2xUJtmyowMsqOASkejTcjewixMPLgGBBqkkxX3YbgmVDy75Xhbo87Wvl1lX4G9mdQmp8+tBPiJyyvyVzK6UPUqXZqa2wEpMQXtozg=,iv:oqRWuhe4gMjEZgcccliq09AXwwcMFqKJLrIsdHrLUyg=,tag:xVWS697FMQ905rIXtOkzaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
