# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:z/Ugzf2zvMRQu3oqefK0Onh/YcQSlmLGM2xSyUyJI+mwbkNb4bA/NX9bPDfDPy3w3414nesOPV3UGQa5AvpMHcZXd+nkNp69JB6b33zs/8hIZ169WO/vUDNIaiLbkQlry28A1J4gQzy3X6kKHQ+vlvOxmecvPHrcmtKWcdJBDKsMhYgH3HxN9oDVRrXB6Ma3S9P9qt+m5d4AQ+8xw/+S7T4S6HLFv44oA+deNqGi1SfrGQ2EOQ==,iv:+T/StwJlBPVbvosXFzZfq4zuR+3lGde47leR0CqtjHg=,tag:5psy/g7RKkPzZFOvbn5Xmw==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UGU1YzNiQUFyRHRCY0Yz
        Wk8rQkZ2WStYQ2FoVWttNWoxWkY5VGQrc3dvCnNpM0FlY3pzVFdXNTl3dkU5eE52
        a082bjhWbTJLdW5SRkJNL0NrOWZsU2MKLS0tIFkxbHRzVHlra2pGcFRkaE9yVlBq
        NDVtOS9QTm93Rm5jRGM5d0VUNFd6WUUKiZEaupkIgqfw/JJCft1Qo2RltS2jIkvF
        dg4m8RNN13ewRjg2GhpuKKAuz5amJbehYyxouMWZwvgzRdSuirhoUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:8R9Qz9+HFgHYuvZJZi1ubd5qN/uwNrkXD0cHkSFV1+MY82mGHDbQuUvsbGyjrSOhGeefnPd99HlNKABk79SKnpefY3WfMxdHVpR0WjVdI4RrkfNwMU7BhXtwYQgOLrNG9xyiYL7FGHOLH4zThBCt2GciSbrJ34z97d5zP0Ry2Y0=,iv:GlAhtsnVrIurZ5W9C2lyf4cFE5HY9kDZ9qco+K4W104=,tag:xXDJazCZIprVll5dExL4Nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
