# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:syXmBIQx4xb7zw16pMhzBj0TvmOU8E+x9/2Ot85DHmLoDi/eTS07VooYIyNMAJIfo9aV9UBT8BIBIeqhWFeYS2X54PhytEJci9vM/64HeyeTXiUT9vI3qJMVxMP2o2Gi8EqqjsoEgzbXWhkuN7Gj6cpzeZgUXOUohBU31Cpm0w4mUyRwVvu8qq+6LfHlCYaol8/DEa3tLRV/eVI+3HewnYtvSVM622to/xm4cgM6TVlZgaFNrw==,iv:yZZUUGdD6sq8BR7Q8nfbcjDeLeaoIF4u3zB8+geoNdg=,tag:VgBOckdR9AR+CKRFyiySTQ==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TXFtd2VCYVQvclljU2po
        cFUycE9PV013VU5TdldOZDVOWUxMb3FhZEhZClRQVzdzcXFsVjIvUSsxNjFldGp5
        aUxCR0FUbDhHTXNCM3ZqVzVvVi9EeWcKLS0tIHc0c05iRlJQYlRWQ3V3TnNYS3hO
        a01UOFVhUjFhaXoyWHVubUN2b0x1UFkKACSXQ7r9fAkbotliYYrnrbnQnlXBUWcp
        FV72H0x5W2CuiJn67nexF0FvtfNIo/ciEwf6K6IUSjiuMU7mrik0lA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T00:55:21Z"
  mac: ENC[AES256_GCM,data:S7tKkm93BMmaXIxtC+4LDJCassm/F3dzzbE6UHcjEYH8AQ/X3fQXw6rE6khttEgPic1Z1vamtM8DOkLKH9dZAPMVXjJq5RsZknGWp+w36jOOFoXjSZJmUJQBfWHneKpyBve7ZXQU+njxe2e8Sq4YuikmVkIjXixMT6gVqxkRF1g=,iv:1U4xGBmaifzGm5EDFuuIGkJRNdlRzdPDKGbE0f6zcHM=,tag:mwAZvq6HZ0nY+q4Q56ze/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
