---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: babybuddy
spec:
  chartRef:
    kind: OCIRepository
    name: babybuddy
  interval: 1h
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: lscr.io/linuxserver/babybuddy
              tag: v2.9.0-ls232
            env:
              TZ: America/New_York
              PUID: "1000"
              PGID: "1000"
              CSRF_TRUSTED_ORIGINS: "https://baby.${SECRET_DOMAIN}"
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  initialDelaySeconds: 30
                  periodSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 8000
                  initialDelaySeconds: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 512Mi

    service:
      main:
        controller: main
        ports:
          http:
            port: 8000

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config

    route:
      app:
        hostnames: ["baby.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - name: babybuddy
                port: 8000
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  remove:
                    - X-Frame-Options
                  set:
                    - name: Content-Security-Policy
                      value: "frame-ancestors https://hass.${SECRET_DOMAIN}"
