---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  chart:
    spec:
      chart: connect
      version: 2.0.5
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
  interval: 1h
  values:
    connect:
      # Connect API - REST API server for External Secrets Operator
      api:
        name: connect-api
        image:
          repository: ghcr.io/1password/connect-api
          tag: "1.8.1"
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        httpPort: 8080

      # Connect Sync - Syncs secrets from 1Password to local cache
      sync:
        name: connect-sync
        image:
          repository: ghcr.io/1password/connect-sync
          tag: "1.8.1"
          pullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        httpPort: 8081

      # Shared configuration - use existing SOPS-encrypted secret
      credentialsName: onepassword-connect-secret
      credentialsKey: 1password-credentials.json

      # Service configuration
      service:
        type: ClusterIP
        port: 8080

      # Security context
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault

      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL

      # Annotations for reloader
      annotations:
        reloader.stakater.com/auto: "true"
