---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: homepage-secret
  dataFrom:
    - extract:
        key: homepage
