# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mL/TOq6msaeKTyJ9sNGDxre1ChwdK7hOPVXfiuJxU9oOpFmePtf6PQ==,iv:lI73WaRdS0ObQBZ/o2cq8iSEhw1SVpy9xcCpmiotYxs=,tag:B0NE8MMyaqWKAcWGJ8oU7w==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnc1pHREpSb3JmZmV2MUcw
        VGZoNjlLYXFmdFRSeSsyYjhRVTU0WTFlSW5RCno1V25JTm5JbW1DVHg3SlhpalhD
        M0U2a1oyZFlTTDkwQXBLWm93bTlkaUkKLS0tIE9Jd3Z5SU1uRjViRnVMUVk4VW1O
        TkpVNUFVaFQ0a0djRlJFMkFmT3ZmamsKQsy/SLlqmF3dzAPSkQ4J5P5A37SkX+Yc
        l3BvbuzhYpyA0uvZLw59bHBoKkMhaq28jKZPnStxOCZNSxS4o5dW1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:FdW1Rr7CqS2t7tkp5lfUge9dwxw5Mn9oHVU901Kjfco+rzQutqExn2eL0unqo7NrecJpEvwV6nm/B7QYbvg3KCyR114gXkWu0hSW+scfTgcs5T9UgfU69Mm4NDEg4e5SaheLE7aKKAgwL8T/FTGtG11RBkO4TPld7HFbSkDstak=,iv:AfBA2GMGkh9sPPAfCciA02qgTbgLEsIQsedI+XAnN/E=,tag:gdWMLlnGIS2M0FZorBq/9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
