# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:eBkFSHir7Gdn8ZQoitFEwoJMex4Fb1yL9XZBbCI5BxS09jqELuQJ9w==,iv:XMTOFJSZsrFZt4deUx99sggPxDr6tNACsxU98/r9rzc=,tag:ajMIZ98C51ybF76U4I8Ecw==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bTdXaTBJL2txaXFCSitZ
        cEIxMHh4S3VsK1hYZE5SUlBYSStaN2l0K2w4CnZYaDllVTU4TEdoUis0MHRmcE9h
        Y1EzYXJ4VHNlM1kxKzdUeEtlTC9TS1EKLS0tIDNoK2x6U0s3NEZtOUhsd2szZnkr
        cHJyMGNEeHQ2YzFmL2FtVjRha0tLQ1UKSbeKN4ajQADKtjAc9Yfdlrhwo5wqKXOR
        LceRV5Av4OuYra4BvYUDK7NSWOHTW4fceni8X3HPhPBDEPefYW8ngg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T00:55:21Z"
  mac: ENC[AES256_GCM,data:lQbVfmlte5AH3kkTr1Ty3971jrRQ/wbraoQjSZEDhI8WOvDDhSjejH+sLdTgAzQqiw85E5RfahtKJVIlN0wD5pmmB2cpBsl3y7fkqauoxlcI6E82djfJOaC4V54wzkRrVUCTCZRx1BBiBECyCUKGCd4Jkq0BZzVNnEGWHbOHQKY=,iv:GfGQVdKf4+XLSZccD65mu1NVgsu2o82Q/isXgDaF1ok=,tag:7oCCAA5oZ0/Wyz+4CKLRVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
