ansible_become_pass: ENC[AES256_GCM,data:vbOhDB9mTMODSOEth/dj9ipG52bs+41UXb6pYT/J,iv:TL8zU9H1JYmLZ1dakfn3lrrRf2XxFQ7qf7WEmpsXTtQ=,tag:sH93KHk5oywgb/oyt3PebQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS0kyeWQwcmgyaXNHcTF6
            aThRMGwySkUxTHNnaGtLYS9XVS9KMmVXR1FjClNsU0ZMcS85MkJXcjVkTTdFVHNz
            WGVvSE51b1NvQ0ROSXI2dUgvR0c0a00KLS0tIHV2c1I3ZUNWRG5ZVXVkV0drOFZq
            Vlc2R1FFOU9ySmdoczVkKzY0QkxnR2cKAquNAHAXrFWY5w+4nZjJqi2f9wCTSddB
            uB99sk+upnvrbM4u4gE0ctu9HoZzNI6rAtrKPj2sbwIAxAvVZ0lOfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:43:50Z"
    mac: ENC[AES256_GCM,data:+QAf36GLs/nxXweqkZs3zS79cdlULbMninUMGZAwUilkL9RcH/NT25Llbg6nq8XWylaHHzj8I0beiybJi+w5A4CFlmtCyfh6oDMipZgka0cAUKneytdt0bpRcZUfHh0Ta7ctmP8BGbvAO8N+KHiijwtRPGPF5K5jJVj0UJfCjng=,iv:X7y4alq7w38v+rsSX+6kyiwQlvD+B+RZVFkOctLSW9s=,tag:sK8CZsqLlt5afLAZWZS4gQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
