ansible_become_pass: ENC[AES256_GCM,data:k538gfgLm5H2wtM/sDqFtH7joZpmw6y15CXKTeMP,iv:vd5llWYSthKWvqi32eUTiO6IICIU45h05dQLVvpY71E=,tag:0jvTK1BX2cVLKgT1oPvw3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDlPQ3JZdDlPNHZ2RzI0
            c1N6ODJwRDlnK25ZV3RaSHpka3BUU0o1ZUJFCmx0Y0o0WHcxTkhkSVAydzJLWWNS
            alZZU2dZK2pmejlPSWVxa0JyaG1uNFUKLS0tIDh1dmdENzhrMXFQOXpCdndSS21G
            SCsrTXlkZE56QVR6RVI1TUdYYmplZlEKTQqWgWKLVcuEHiSq+hLZdMWyfDZB6aOh
            M2ccx90S3o2QYymP8Mst7Vr0+8QZgB5YizUL32ngKx8Lj6Oz6hNMWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T05:19:14Z"
    mac: ENC[AES256_GCM,data:a6+at7K0FSxYfsFT8wg9esu0V56f87JrJ6CAG+G2l2lWtg4kG9pW0+rasgKwYLjz74u1uWupHhaiZAvmP5D4ilQzfnlLnm+nzc1MrjA5GArDSrBmFAKMA5zRbJz1prhhI3J2c+VQin+WupL3plj99WrzYUP8ErtqkvHSXXpkHAw=,iv:S3EzOkrRqVNDqqRQDKSFoLqQ+SYCPyzyTmMrOAZEzrw=,tag:j4UPzXiQczPeRyqSdket3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
