apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:RuwKDPp4IEvjEW+Jwz2qm/WVAb5T9ywW,iv:hUZlB2UtAlKiPeVyw88/1H3QBymoMM+JgybkwSRANlg=,tag:HFqRKirL8hQk1fAo1Cnezg==,type:str]
    admin-user: ENC[AES256_GCM,data:l4SgL2s=,iv:ajcX7ozmCEweGo2YsG/VYynQfi8K+y9vmxWj+boIedY=,tag:09E4OzQEFYqkr/D2Ed3dfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiL1puTWRyM05xTGlGSXEy
            WWlGVXNBS0JaTThWa2dsL3R2eG9TUzlXTDE4CkZKUTM2WDhkMkhYcVNvaENCZ2xH
            YkVHVStUZncxZ2NiR00xUCticzk3T3MKLS0tIGgyMmlvTlVKNXF4Sk5Rc3g5UzNI
            anZpWW5DMkZZYjA0WkRLaCtqcTJCYncKrbfIoCLNdika7qtMSvCoT+IapiBb5gDw
            B3qs7lh2xq4h6bPEqa6Zsn/7yG9Q2W5T2uVZYYzxdjE/nhRUnXTheQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:40Z"
    mac: ENC[AES256_GCM,data:75Hji72d+DshKH05Hd1cNDzhLrjEIN0u+Basunf6Oih14tTjcVnrTFVrTGRQYB0b4LoJfZCXs2KCfIFaCW7LnZZTJDAYzLF+vDOY1uTprXp1AaOEXbzBieYH1f1BYi+tcs5fhfziMPH3wTBsp88QB3sS3F8V7g4Lt5d2a63qSS0=,iv:X1HKR/ubPPhxrjxK4Tbmfl79q+hWJG02T0rO+V0Yp7M=,tag:xAO2nuGAVynLxmL5JXXXXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
