apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:oJM2TiPc68ITVR0ZGFzJnHGKW9DzVoY3,iv:pSxZJ+n+5/5L18oyFV0NxPQoGNTeNU98PbV6m/1vnU4=,tag:WNA9n/1T3xNlDBPQtG85DA==,type:str]
    admin-user: ENC[AES256_GCM,data:MS2KAEE=,iv:owgremRgrshWEL1U8TbxWDobNaZiZW2VSQKkz1b0Gxs=,tag:xc3fOuRHTbMs6iO99rinCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQmNSVENhTExDWjVKeFVr
            RjFmUFJHNDhaMDl4MFg0WU5EL0VYNXV1VWk4CllwaUlPN0dmb09LMHJyN3VLTnc2
            aU0rWWJWOVl0WlJuenBUKzhkRVRQL3cKLS0tIGJEc085MjhNVDA1MSt0NmhQSGll
            N0Q2UnJsMjkvYlZ4Ykg0WjNtSWFnL1UK+59re6Y5duK783fvPOVk1jPh5wTEQ/ZU
            eMHK/7KKolYUj3th1C1kCej4gtVgokHmVGEdxeYfval42v9doK7HxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T05:20:04Z"
    mac: ENC[AES256_GCM,data:dwwH06Dkr3O8JtnmKz3PByTlhzs/kJP8REGcsKHyyH9KzlJ5zuMUZ7bXme/ojFj5KdrDQD5tqH768RdwH9UU6NtdiUjTp2TvLytEG2MilRFADzmNJ2HskqUrxf3Sx5wJSlg1e6nbxynZOWA/78SErHcVd0znMcWrKjdFJLeJ270=,iv:paA5HOulMPeavVT1JKhbTSocZpON8EkpxRNwNCS8mPo=,tag:wWK6EwEAzE9aD2OCrB3UOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
