apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:kSdTv9A6j95QvpmnfcBQoeFaQSvEjTTw,iv:0de+QrJreBqO7RwSV2KK0Os5ZnZkXx777BsAiEvIJoc=,tag:kUGFb/X0XYyyCs+K9miDcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMkxZaVJrTEVOV0lvOXlj
            TjNWSEY0SjJjbDZVZ2VSbnZldGdueW14MjFFCmdEaGN5REZnRjA3SDI5eWlqUlVF
            TFc4dXo1a1VDeXVJUUZmRFgzMFlGekUKLS0tIHB0OW1aMEc4QXNCYk5DajJtVHQ3
            ZUlqWVFwTFV0Y2Y1Rlh5MUNIaEl5ZTAKOIDYTes3JwsFoyUux+uURgqVX8mDzX16
            p1sr9zeoQfojJ5NpQdUiKsjBxsbWKgj6Ry+aJSCuCTtKTUV1Vskhgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:36Z"
    mac: ENC[AES256_GCM,data:qi7CEv9P10iitbYhFJqMAKjZzXwgMY6LvJAHs2tgvFPt8LfXV3TKUkPTe/pw/I8AfPPRJpfEXT+tF7zVs8Ok8fyg+JtU/16qrJ97U3b6y660AZDST68WzTag6eaWKaAOTshOoM2DK2IXQ3eKZdrRpfS7f4MuXI2IKF+6RKenhYQ=,iv:xLmOOqjXReIVOVNk/UG4gaHGln/oly3KWUjeV6fe4Gg=,tag:ajIP6LVDvj1tz1PQUfDnLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
