---
kubernetes:
  children:
    master:
      hosts:
        node-rpi-m01:
          ansible_user: shawnmix
          ansible_host: 10.0.13.31
        node-rpi-m02:
          ansible_user: shawnmix
          ansible_host: 10.0.13.32
        node-rpi-m03:
          ansible_user: shawnmix
          ansible_host: 10.0.13.33
