---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./configmap.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./httproute.yaml

components:
  - ../../../../components/public-access

replacements:
  - source:
      kind: HTTPRoute
      name: tesla-pubkey
      fieldPath: metadata.name
    targets:
      - select:
          kind: SecurityPolicy
        fieldPaths:
          - spec.targetRefs.0.name
          - metadata.name
        options:
          delimiter: '-'
          index: 0
