---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: atuin-secret
    template:
      data:
        db_password: "{{ .db_password }}"
        database_url: "postgres://atuin:{{ .db_password }}@atuin-postgres:5432/atuin"
  dataFrom:
    - extract:
        key: atuin
