# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ehXHfByvsQxpHA7VUKn+6sr0WeHyzK6ppByCw/4cHsI=,iv:fBm6KSSIZY0gEBH/MjfW16HYhib84eDEhHJ7JRxxJIg=,tag:muWNx0V2W/YuGqKzJUSpmQ==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M1BpOFZxUERJTjBoR2pT
        dCtLWHl4NENiaGpsWG1scEpqNUIwSlpPODNRClpSQlF3VkEvTGljVGo5VzJtR0M5
        bE55clo3bDFLeXNQS3BlT1lTYzZ6QWsKLS0tIFFqckdPM08wMHpQM2UwYUw2TUU0
        Q1FEVmZQVTVEeGNDVjdjazR2VWVBTmcKSanVZAwTar3HEyrOKYYeoDgnbLzw7xA3
        ZD3lXEK4fawbFu1e5QKScd+BmbNtb1Lgsg49Y1DT9T5niofCqClwUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T00:55:21Z"
  mac: ENC[AES256_GCM,data:bqjrj/0i/cNDkgSR3YKZX5MOCfoSZAYmT29xQW+5OVmA4/3tNoV6KFKSZHs9PG/ajd1eo35ifne7oyuCkQzrxNV+kl4JyJmdd4GwTYxCVLVhDdSWoGYWV6ARy85Q8ZHhSIDVUlSbwWxUUFr2EbnmEaUDNVFJIbzQH1phA5ttrc4=,iv:V9gBFO7bcWf8b7HwUEdGfy95zjBGmFQMUFSr7eYHpsU=,tag:eEysnpLk6HUUXx3g0YbaDg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
