apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:3P/3GG9G3YyP6GQ2p1N9tOwMq9KXoHKTdqxXmbHofJ/U6izSGXuWFNGqL2zKYiLnw4fKlIy6XwDAUM4NuXV0+w==,iv:0nGW6K4Z3ciK3FvYkwWPc+NreqPzSx+a2INHRjx46nU=,tag:7yW1z10nL2bKNKbZMAEbmw==,type:str]
sops:
  age:
    - recipient: age1azd5x9cmhpaqn8ww60q7yqwc6dhlw3z66cz7mjwmnkfqdqf0lytskc8asw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWk5FazhvTGVEcjMyOEtQ
        SFNLcmhIVFdWMDU2Q2FGbkk4cXVreGFPN2xnCnE4bXh2aXN5akpmQ3JmY2w5ZUN1
        SUlFVkdkemhNSVZ6Nyt5alFzbzZnQWsKLS0tIFVOdG4vN1praEFJK0paNVFSaWMy
        TWdMQUtFMXFQY3NXSExrRG1mT2FEblUKTOXA1TZiQuWRGoy/+T5HdiSRbMP6akcA
        cQcJt4uVGQ/mWrgKM/Kqy9OqfoQB1Ha0HGLFpq0lyrhHFKMjFijk4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T02:46:29Z"
  mac: ENC[AES256_GCM,data:3jPipiO7WmoNd9QUqLolrhGyISi8XCDIaTGXN0q46m164Ocj3MFzgqtcRguZdMXZgqM90mG6NShsROGEgU9bzta42Tj9BObslE+w3AM6Bd+LkQ1UrFSlfvszCpmMOd3C9IYhQYVwe93PyOSfj3QcUNoxYWOYjlhHg4gBz66bm+g=,iv:fSaUcbRKllCWweoG5ZQ9E4L2ipwxls0ok1+K4ZXpaII=,tag:z3kbkeHt13cOkYe2GRjjGw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
