# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:uWG89qBq2pXTnACiKnwRzoq4NGxLvC0VHgmBMBbhDFw=,iv:q8AReJe8B8skl3sQUUG4LLUSc6vsMqMeKCx8rV7EXGE=,tag:K2GqSk+lCxkLFr9s8xeN7g==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcFpmOXoraGg3UmFpYk55
        cHNtOURPMk81YmY3elpDRmp5SFpycEZXNnhFCjdhRkV1d3JoMGRlTFM5ckh1SHZT
        eURybGxqNTVYNzhxbkJqOHQzNXl1OVEKLS0tIForKzZ5STB6NWVZVTFKRVRDWEI3
        REZqaTJaMk1URUdhS2NHWWM4QWh4MEEKhh+py3GCd1nfjEey9Iu67rQJ4KByxNyG
        7RLh9nw02E9RFJc3MZKCyoNnglrx9gCPSUIXgIuEHA5T7U+sQKSIfg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:gIB6yDgPQHhJL5uOWj1TOSNSh88zbSIBIiqk6wopx6LlJUDp9tWoI4h2SZpGmV11Tpy2WIj2qaLvqqiuZVXPk/3f4HrVR9L1chDJcOid2HdfNuUZQorz18VpN9SVTqkQOenAykU1tf81QbptO72IWeJiP2gkHMp08U7UV/B+x7w=,iv:M4TLM1Mhk9MVQVQIt17TBBTOkFFEuK5l267GFXp7/mM=,tag:pKw9uOhBKuteuB6iD+2oRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
