---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  librechat.yaml: |
    version: 1.1.5
    cache: true
    endpoints:
      custom:
        - name: "Ollama"
          apiKey: "ollama"
          baseURL: "http://ollama.ai.svc.cluster.local:11434/v1"
          models:
            default: ["llama3.2", "phi3"]
            fetch: false
          titleConvo: true
          titleModel: "llama3.2"
          summarize: false
          summaryModel: "llama3.2"
          modelDisplayLabel: "Ollama"
