---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-config
data:
  recyclarr.yml: |
    sonarr:
      sonarr:
        base_url: http://sonarr.media.svc.cluster.local:8989
        api_key: !env_var SONARR_API_KEY
        quality_definition:
          type: series

    radarr:
      radarr:
        base_url: http://radarr.media.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
        quality_definition:
          type: movie

      radarr-4k:
        base_url: http://radarr4k.media.svc.cluster.local:7878
        api_key: !env_var RADARR_4K_API_KEY
        quality_definition:
          type: movie
