---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./db-backup/ks.yaml
  - ./forgejo/ks.yaml
  - ./shlink/ks.yaml
  - ./apprise/ks.yaml
  - ./artifacts/ks.yaml
  - ./bridge/ks.yaml
  - ./zipline/ks.yaml
  - ./homepage/ks.yaml
  - ./glance/ks.yaml
  - ./rackpeek/ks.yaml
  - ./atuin/ks.yaml
  - ./code-server/ks.yaml
  - ./webtop/ks.yaml
  - ./nextcloud/ks.yaml
  - ./mattermost/ks.yaml
  - ./synapse/ks.yaml
  - ./mas/ks.yaml
  - ./element/ks.yaml
  # - ./syncthing/ks.yaml
  # - ./kms/ks.yaml ## Disabling for now, likely to archive later
