---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./forgejo/ks.yaml
  - ./shlink/ks.yaml
  - ./apprise/ks.yaml
  - ./zipline/ks.yaml
  - ./homepage/ks.yaml
  - ./glance/ks.yaml
  - ./rackpeek/ks.yaml
  # - ./kms/ks.yaml ## Disabling for now, likely to archive later
