---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./zwave-js-ui/ks.yaml
  - ./matter-server/ks.yaml
  - ./home-assistant/ks.yaml
  - ./tesla-pubkey/ks.yaml
  - ./mosquitto/ks.yaml
  - ./teslamate/ks.yaml
  - ./teslamate/grafana-ks.yaml
  # - ./esphome/ks.yaml ## Disabling for now, likely to archive later
