---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secret-printer-secret
spec:
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    # This is the name of the Kubernetes Secret that will be created
    name: my-test-secret-from-1p
  data:
    - secretKey: a-secret-value # This is the key in the resulting Kubernetes secret
      remoteRef:
        key: my-test-secret # The name of the Item in 1Password
        property: password  # The name of the Field in the Item