---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-printer-secret
spec:
  secretStoreRef:
    # Assumes your ClusterSecretStore is named onepassword-connect
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    # This is the name of the Kubernetes Secret that will be created
    name: my-test-secret-from-1p
  data:
    - secretKey: a-secret-value # This is the key in the resulting Kubernetes secret
      remoteRef:
        key: op://home-ops/my-test-secret/password # Path to the secret in 1Password