---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./cronjob-atuin.yaml
  - ./cronjob-nextcloud.yaml
  - ./cronjob-shlink.yaml
  - ./cronjob-zipline.yaml
