apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:g3WC2Qt8spW+hC0JcpwmjWu2DRmlb/Nd6hM9A6oOqX6DyGqFrkcn6Q==,iv:gLQM9zSACNyr5i+M+EU34hgd7m8QzCy7s62bxIequLM=,tag:7Caz0SP8HV2bHjoMV/Sdaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYWRtMXE2YWRhS0FCOVh0
            Z2UrWk4wODBmTzZReURuV1RJaTFvMUw4b0dVCmNHeUVLSTdTWHNKbmsyTkZ3Wk9O
            MmIvNXI1a2o0MW80cUNYcVRCbTBXc28KLS0tIEE1ZjVnckFibTBFRG9GYWtHWTk3
            T1Jhc3hPWVdBNmUrYVM1aU5kek9wY1EK2nFRMNf1CEdBjQtrhlpXHY4L44lsKjoL
            YG/yfFwN0D0HevrJXQYnY48k6pJqXycjEddvSgs9Xfhwn1EP1BRzIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:36Z"
    mac: ENC[AES256_GCM,data:Gs+ZYRYi7eSqS8yOYBmp2O0ZB8LaWzZO3YZw7+fWqTNvbS4+WB61yiFkUcDHA7NXjMTlEI3I+UxN8ArjFcjhsyqOsoChwaS+Dj80a3gaTQQrJo4pI2hwo7xF9ndecdVxt2AwgfR5hkhvE3OXjJjurTQFtm82yyytk4aLRoRDXfo=,iv:63Q2Hi4d7kT2wzTj47n5+rb9f8NwYrXWBkYa8xLPQdw=,tag:zmHNBjRdzDXK9C9SzwaA0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
