---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qdrant
spec:
  chartRef:
    kind: OCIRepository
    name: qdrant
  interval: 1h
  values:
    controllers:
      main:
        containers:
          app:
            image:
              repository: qdrant/qdrant
              tag: latest
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 6333
                  initialDelaySeconds: 15
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: *port
          grpc:
            port: 6334

    persistence:
      data:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /qdrant/storage
