apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:DPnt92TRm0Z+ryrgBMKJIX+UOsMVlH6nC8x/knEdt2jtbUP4SzO059Od+y1Wf0z/Trh3KVvzRkAPfSOY8IReWp0bMl3Az3TZqkDceGJoelkJTI7K0F3moEjktt1OQgxctJBYlIXaAj7byEUKCAmVuPpp9/EcOaZvf5eLKFGbVsbfmToSay4tCDrlCtXLzvtgbHL3M1NbFBUs7/Kx68JD5TeC5l+r9Oej49GUYpqL1MToi4ZT,iv:L983rZ9eFPsTcJXIA9SNH4+ELZAqI/OJzyEZohz0IsE=,tag:b7vE1CR6K7/btqDzx0QTtw==,type:str]
sops:
  age:
    - recipient: age1azd5x9cmhpaqn8ww60q7yqwc6dhlw3z66cz7mjwmnkfqdqf0lytskc8asw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuZGZrT1A3bG12aUxIVzRk
        SnhHOUdlOHdPcHJLaEhPbXIzSFdrdXZKcDI0CjRzakJuT2lJTCtOSmxraUQwR0Zk
        b2ZIVFBsVjZWQXd3cWJtNnYzZ2llTWMKLS0tIGhqMUM4MWE1WEdsN05kM3RDQmZh
        U2JvV015SzNEbFltTWIxME0ydW51UlUKswssIBsC2wjrPnTLWA8ChQ/BdiyXj+FD
        /REnAh0ToGjnkZS6I28N5JzupYizCh7p8sQrmvWlEFYf/zx1Nj+8Hw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-27T14:22:49Z"
  mac: ENC[AES256_GCM,data:/wRYLKDAyuTFpseyJ/1FU+busOzi+OOt8fvwBMD97Pa44SS8LW9SWxA/5BLWISlTqFGxSnRQzVcdUTmQlAWw3bAVTno0StBhwTucq6Aqt1RPmsar0XvQLa8Vw5Ic0f+S7J6E1l/B3M+T0e1DD6W8HMo5dOYKByQs4dS96bZIlFI=,iv:P8+uaAkrNlNWZ3XDvdakzH+Qo9ya+Z91aypHTIt36fw=,tag:kqiOt2xRLOu7rM6b0VMN+Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
