---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: mosquitto-secret
  data:
    - secretKey: mosquitto_pwd
      remoteRef:
        key: mosquitto
        property: mosquitto_pwd
