---
timezone: "America/New_York"
github_username: "1activegeek"
coredns_addr: "10.43.0.10"
kube_vip_addr: "10.0.13.40"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
node_cidr: "10.0.13.0/24"
