apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:5hjZN+BWkBk7XTenRvqLKCe9DrL61cpvQ0S1EOPMIoLVFLh32RavvRl9Kjq3ss9qoQdUvGxuRK82naep,iv:NppBrEOmRez1xxAwFqfplzC3Hh7iQcACy5ZDqoQYPbI=,tag:ER3qXWWLR2B97zQs/qZ4gg==,type:str]
    username: ENC[AES256_GCM,data:5plwwpA=,iv:EwFLVFpf/xw838ZHDdRqJSCyPflcJcgNACCLc0USoFg=,tag:ZkeF4V2mSGaDdJNH3lR3MQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVmdWZGhYa3MrVTh1Y2tZ
            Y29seGRHU2RFZTRJWmdnMldPUjBWbnhxMFY0CjMxb2Q4ZWZkbldCYWM4cXpMRDk5
            dmVHNktocmxqS0QwdWM4c25qYmhpdTgKLS0tIHpRSWNtNmNtdmhHWHpKMEtWVmRW
            YVlKckdXK1BPSWxnYmVuSTBSYUxPNVEKlWyonEGWO2Xs5P7P6Diep6RX8e5eI7wI
            e12392tJLv4tulbg0SgWQHK+o5muljsBmrKUviTMlV9yXjRgcE1Xpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:45Z"
    mac: ENC[AES256_GCM,data:FRKShI9BuzikwDK17sRGyxyDX+WN0DCYY74smPIdSVe8a90mdMD/3KftvF446krWPvCE8wnjAoQpHQso2v4YkuJ4nmcSYsSlweccItkhqUGJwS6iEeuCpdBHzawjHUm5SYlQLuu7Aii4uWt5GJoDIL2X6d6NX1wOdrhsP6FwYck=,iv:PBYUGDRNtfMTp4gSqcvYH6zm9miowUhPNAZNpXgz/0o=,tag:+xoiaV3ZfrtBZjM7Hpg6aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
