apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Ac+OCio3WXcOUf9phbVMCA==,iv:wVi5K4U9UB3ybDP5Vsz9x4yrjUqENV0rRkobL0upm0c=,tag:y4spfNPjvyYAZUmm1avQUg==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobkx4LzJSSXlaVTg1bk9D
        RnpYYmd4bDVDZElwSS9rbXZ1aUVoZE84a3pnCm0wNVhkdFZFY3JhbGZ0U25RRWcw
        RTBQeURCWUY3YXgyd2tsVGRHS1BaMGMKLS0tIFd0RkhoN3FqMHVWYlJTRUZZUTdN
        TktiZ3FxbzZHOUd2UDA0TnFFN0VIRDAKrg0BoqbTsy3l89c1P5Ae5Py9N/2brile
        0ANk9rE+VsoUswNG2mJ0z82ZrHzJsyBE9pRNvGOg+tF2mip79Tzclg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T00:55:21Z"
  mac: ENC[AES256_GCM,data:+msqHBIeMhjslVa5VOgMD+oWf5i0uwwoG+N1/8D6xtnez7PkS/EwPlg0ahbKykV8NowiasEAvfH75Dqp8pBQ5H1nULHQlRspW41UPR3V8Uneod14PP2JluzsSexGk900ICY1K+D6bHVFNzuM4mVNm8GJfBqxtv24uUPti9AWDF8=,iv:LeZVhq/n5MqfE2j30QmzmpR8+G8ayIjjUTQdhww4mxc=,tag:dQ+eCTxrsJ1Z7NLwCIpFIQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
