apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:us57+m8MRrGGbK7rs2bUnA==,iv:N10yWwlrRt6lVP2nYtBbCtk/KhkV5jkdVrXLPO1hwgs=,tag:tbrNV8l42v27K9sCssYHIw==,type:str]
  CLUSTER_DOMAIN: ENC[AES256_GCM,data:J5cyqcxJdBlpHKrAm86Lew==,iv:U8BQIvlwOZ9ximcwQcj3kZAEL3X2QhY3pZKpoX99Reg=,tag:rR8qnEFbejsVOlPPnEYzvw==,type:str]
  CLUSTER_VIP: ENC[AES256_GCM,data:B6vSpYev65Pd+g==,iv:ZxQPOMnYOoxmi0yPuLnzm8y7CPKq3w8Sj7zo4xsdZjo=,tag:rXYPjXRlwHZFAfx20+iP3A==,type:str]
  CLUSTER_NODE_1_IP: ENC[AES256_GCM,data:xasatXdpf7YdPA==,iv:QHizWE2ie4+kDUHDg4cLTUiJ7lZxXhBmL6DlmI95YUQ=,tag:zm/kh0QnvbaB1Moe7Bnl0Q==,type:str]
  CLUSTER_NODE_2_IP: ENC[AES256_GCM,data:FmAdFSTukKz3pQ==,iv:55ul3Mqad+eE6UdIZu7vzdIV8GU8no1nJpYAQpxwWWc=,tag:5QBBbd2az/aFrVWIGaXCaQ==,type:str]
  CLUSTER_NODE_3_IP: ENC[AES256_GCM,data:MHeJfCtHbb4cSg==,iv:YME2gPGiL+W7we40o6xECzzSo6oWmSqcecf3R4gyMyM=,tag:kcB8UOh9OPtTCG+HqHr8dg==,type:str]
  CLUSTER_LB_IP: ENC[AES256_GCM,data:0OGs4rL4MbN8vA==,iv:BZk/DJELtSh80pO1V93hMjco21tN6N7CApv1e9TDYGQ=,tag:+0DeJuWppgs3+FloAc+nkg==,type:str]
  CLUSTER_DNS_IP: ENC[AES256_GCM,data:VQ5LEIyGg6Ee6A==,iv:oKAMxvFBI/AgkGWwi//7GHWxLW+v3mx23ZU1rFCcFVM=,tag:RE5klF9bZeSF5oUEbr9eoQ==,type:str]
  CLUSTER_POD_CIDR: ENC[AES256_GCM,data:lkhkvpHBC/LJRBme,iv:HNcTtWeO7ymsIpjsvxrJoMeiRrsY/vnfCKCTTEHyrog=,tag:hNAYAHV2ODzs2FrFFZ0esQ==,type:str]
  CLUSTER_SVC_CIDR: ENC[AES256_GCM,data:dM4gvzrnsmi3zA6x,iv:oS9f8WOGCb7YAwhziqNpTJTf8wrcuZMyJrM/W0u/57w=,tag:9aLv7k4qhMi+g50Pcbvdnw==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPdWo1anQ5K0k4N0NEWFd2
        bHA2OXRoYVZXZ0JQbHlPTjlzU3d0czJGS1RRCjVqNWd3ajl1am9QVU5pWW43dW5F
        SDBlbElEQlFTNzRrSENBMFk4V3YzSjgKLS0tIC9OZGRlUzRRdThFT1VlWFpPeDVG
        MXBXLzBkNm1mZzM5MzJLNFI4cTRvZkEKhKlMoF0xaFzZfsZeHy9MDfQY6Ihgv4tJ
        RDLZ12iPPZY5XxH+EP99e3VWCD1YiaGmNGiMYxzMLvKtZd0dzMmpuQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-24T20:27:17Z"
  mac: ENC[AES256_GCM,data:qGVIgzB/QYVXpTpObbd+URTgMUj73fn2H1FkxgvDvcWt66YRQO3AjCvF4HgU9+6Lg0w2ESYiezomPOjmQomFNTdS9+SkoAsLYEMq3GldfMYNtNd0rPuPk7z1w0UJORETvFvrH8yDO2CJlQtND3hiBx6UrzZpkAF0U+7MZS/bRNY=,iv:Jp4QubmkFxwI9aMEmodEm6lOQNPyZzB7LXTcKDFD5xg=,tag:cWhVakTuoA6riwKSVNzM+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
