apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:0HKZW0wDewcs/Eu+EsZ4hQ==,iv:yUElTi7zk5tiAjJOkMbAnOd83AOfaC2pOOXCl5H5DP8=,tag:nqOL6GHR2qJEwJiP0iz/Ww==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSlVnZXNXd283dW1oRllW
        NXg5NE1keWNKbVNQdWNQRmhWKzVrQ2o5cG1NCjRwcFE4QTdpemU5ZlBNV1EySnln
        cTNuSFVMWnNuS24vR3ZtOHpSTlRXa3cKLS0tIE5yMWJIVVVjcFNkOFR6SmhkSGsx
        MDJhR3hwcnl5SkhXSkkrdkVuRFd6aDAKBNHO9+vDKOkB4KOue6gsL3vxG7qq1D2L
        H/xDpBeGasVQZVDZ43vbO5M3Fe2L6Z+CLi21qxg0APreW4OOElDcWQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:1SVSp1qou1dTXQG1riSB0r3u2sNSvEVOOn/f1caWoybqJxLRMss42FqLdI4vLgsQ9g4wIrMnEDVIp2PwBe6gHgUP+ZhR2p1Du3nDOEbpaV4+GXfjOE6NTINvenBfXCoMT4Y8KampukETe9xxAiBvkc7boljaLTk5ZIBDvGQjNyA=,iv:oc+Ll1NR/2sHt1sGFvlirCecto4A5WinbaXInixjfgY=,tag:uGt9msx2AtIqId/sL88NYQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
