apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:zyGSHs5e/5nC+HGJ0MuHV8ZomXNqX+0b2pC9EihvcP3mskdBrGpcDFQbmJtE6bVr/E435jA1OaRktOCVWNyDpNYzNkQ640THpPs=,iv:q4MIG7esO6MfeeayZuGM5FgDzJkXbZ03rZfPAdW8zJ4=,tag:PLHz6lO3zonVecku2Qu8iA==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dmdMWmpVS2RLcEV5bVJQ
        SVRLeCt1WXhlcnVldFBZMm1Nc1BnUXF5T3k0ClhjNldRRUVXQ2hpZmRIblhaSTBK
        cFRiSWhrUGRobzhnMDgvRkxHTEJXMUUKLS0tIHRubTRCOW5kWTkxRDNHREMxMXpH
        c2s1NURsSzlLY0MrWW12Tms1MHYwT0EKhu/ZzQZb+rO6O2gk253OVvKuJBUQj+42
        fG6DK3J/uPlJNJbYJfv4gQY0s57tietAr6yMBaTfm7FZUi9v1wzVXQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:H2JUB8gOPThjYJh9PwiuCXW1rQxC9tkSpMwHbchuE+OmHIxc6BoFt7ry/h8qnQIM8nJQoKMi+X0mp7g0F2wJLRH2gHlhjaoHtgP/SBQBc+DJfBfK3QJDYb8kRtF65iblQm5A9LJ8Oy6wALvTXe+MmDIRfGcs6sJ58MOSQYYHmeg=,iv:0pnH8VlMyKWVLnNWcik9i8xvFgYl4XvaVjwi27PqE7g=,tag:KbZVw0/uLcuK98k7CyFJEg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
