# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:a1ejj2oLatg/iKdYXsEJfmXGTT/C0jRw5CBUv7oltQOuFfankCN1bw==,iv:gEIIi4fpk2Ptlvzza2YEZtY5ZbXRg65+u8roWRqg37U=,tag:4ngq0BHj/PkCGLtfPxuhVQ==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMWpjMTIzM2dkWTJXUFAr
        YVFFdUtoZ3hEbUtMQlk3SVMrS3Y1N09CblFnCmtocVkrQnFabVZiZ2VFWWNpd3Jt
        Uk4yanRWY3JEM1lST0lqSjc0djRrbEUKLS0tIGJiRDI4YTVlRzJsKy9ic3V6Ujd1
        TXIrT2JXQ3BHR0lzMmNhS0Q0Ry9NZzQKWBD6paW11VpTfIJGNLQQQLt3wH+dFF/u
        u0K0BZfP6me5/ffRNPOquaTo5kdtfq40D0NFOxy9QNcqx3cxYa76fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T01:20:07Z"
  mac: ENC[AES256_GCM,data:cvacYzR1DxewxH3h8bo55q/zO365G6VQ1jC1bWEv9oYY/I+176Q9ohg5riLtFep1rK9+8y1SMDBwkaeSfDHwjrgL1St98L6EErQUGVWF0Bpzj2LRqV4Xb14IoWOsWAQXAVHo2tThw/VPcIm0LFTiZvMMCGSOA/HyukMXptFoXjU=,iv:LPaibbETIEaXK/iVHCO9mkotyEl0Vsw4aEciyjeOaLA=,tag:hVkyDPNx/IzaQbgbAXr49A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
