# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NJ4xQMdnHsNuzsqm+7gmzRjpej7lhNbCS6cxZVsyZmkgzJRynlj+aA==,iv:1ywvgkdbF2he4oYnp8au/lANfCLV/vsQ9sL8aOtYmqE=,tag:uz3HwJT9QiobOhyluY8mYQ==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvYndYcStydUdGZWdrS2pK
        ayswUU8wTnNpbHNTTEg1OTRneHMrZklISWpnCnI1RHdyZVMvRGxkSWtpb3g3TnlS
        d3lUZmE1dnBYM1hQSlZWMjFXQkVQVE0KLS0tIDhsdmw4dVlMU3g1YmxuQUYwKzU0
        NFZ3cjJ2WlZ0UWZVMGV3TlZDa3ZJamMK2LvpunG3YajALzg3WVsgKRCAmC99K5Rh
        UxaHHUpRtG58sUF3sPSnFs3hcgQqgvdAN44AaIhDopUqmyJyS8SErA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-02T00:55:21Z"
  mac: ENC[AES256_GCM,data:tbW5wksiP/hpkkzXXKZobrQcRSUruePDyIJxGMK/SkEN5k2tY+JWBRPdi8nVcrD5IaNqT2CVq4jUSqgU6grF3jP0pkx3gPhgvtuyIfWoahR+rgBTLGUOrV5Crf9tiNfTq2fWzozgJXfyoAQlSmvFUFX6PVJqcEn9FVn0BQ62V/s=,iv:NhmMbdfsK8covTDRM9S30MrDPwvcEM7Kjqm81shRXNI=,tag:4dX/b8sTV4wdoQTY5JFgzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
