---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: alertmanager-config
    template:
      data:
        alertmanager.yaml: |
          route:
            group_by: ["alertname", "namespace"]
            group_wait: 1m
            group_interval: 10m
            repeat_interval: 12h
            receiver: discord
            routes:
              - receiver: "null"
                matchers:
                  - alertname =~ "Watchdog|InfoInhibitor"
          receivers:
            - name: "null"
            - name: discord
              discord_configs:
                - webhook_url: "{{ .password }}"
                  send_resolved: true
          inhibit_rules:
            - source_matchers: ["severity = critical"]
              target_matchers: ["severity =~ warning|info"]
              equal: ["alertname", "namespace"]
            - source_matchers: ["severity = warning"]
              target_matchers: ["severity = info"]
              equal: ["alertname", "namespace"]
  dataFrom:
    - extract:
        key: discord-webhook-jarvis
