---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: alertmanager-secret
    template:
      data:
        webhook-url: "{{ .password }}"
  dataFrom:
    - extract:
        key: discord-webhook-jarvis
