apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:v3bM7QIRMFau0ITb,iv:7Qc96DAW+U7wEHBaTvfAbmS23GzvKW+3+STLya5Qg58=,tag:woxFE7cU2NQuFyZEAhe8oQ==,type:str]
    SECRET_SYNO_ADDR: ENC[AES256_GCM,data:UfqAx9pSI0UgjQ==,iv:qKGhuyA9FqQ4i/WHQA6yY9xU9fdc4J9wLzzH/Z+md70=,tag:WYGA82IFWlL6EESMLvU1gg==,type:str]
    SECRET_NFS_SHARE: ENC[AES256_GCM,data:uhtbj2mvPOeKbjCpi0A=,iv:5i+659pOjMPOshrb830V+L4Rkt0Q3Unw3gP71DgOl4Y=,tag:m35C1hlEreAjRS+CVGNmHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU1ZJakUyOXd2OGx4VXlh
            YjJSNUt5TklrODlEOGw5SFM3dXFmNUlCMFNzCmVDQmUxVlI1MTUyRlIrN0o0c2sz
            RjYrdHJvaDJIV2RGY3FPQm12R2VFbkEKLS0tIEhZaERvVVNNQWhhSlJQbzMrNTBJ
            MEVCa1Z0WTJVZXp4bGdhMWRRNmRZZEUKH0PqhctBmcnAn/mcp6XPqfVSQ2CTRO89
            DGrorVjFnz4MQqPINFB9HDLCVgo63o5ciE8zcgkJFpvFsuzb+Ci/gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T01:07:20Z"
    mac: ENC[AES256_GCM,data:P+v7QbarrJzCalssFvyENlNDf3JzdCCsef65CImW8odZKKhh4VgYz00wcrL/PCUPR/kw3rTtENpOpWsvqZe7WCp4QWggMXk2As1CMIhEWZDpqKVip+yAOjRhdaGmL6L3flGZDlDz2shmvzlwlqUft+yf17EcrsGgiIVBTXl7cWY=,iv:XahJziIY1Jwwwo5W6tkTA0Pp24bWDOODkKr6T9Q9Y68=,tag:N+KTvyevfIiKSRo3S2lvAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
