apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9UCIVxGs4xJXpTZgmlW7H7Y0,iv:1PnB8UVuvOvUfDpgv6GKwWt5R8ji7JdiqQN+g5BzH+4=,tag:p7d06qSMKWlTaMHBqidyGQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:baXWEzOq9GU8taKlsOkUP+iBKgPBKAyg1XiKgj9AcviU1P16,iv:J/8BX3uwM3lmhVkM+KxcES9w9QhRpEGye+Qy/61fUqI=,tag:I0hBcTP6fCuEIpDxscqPEw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:rHpqGh048DiWeRqMNyQmDg==,iv:Q3QVu+vKmEwFkQrowksjCk1n8xnIpoA0xSSpEs6Khmk=,tag:bzjrBqlx6IczJdohS987rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMEJ6U042MEJxK0o0dE1z
            cis5K1Y2a3B1OEpwSGpSYkN4N0tvUmc4V21VCjZ1eWRBYm5QdEduWHpGSWxyM3RN
            ekRyMkRyc1ZwS014RHBVTkI2YWRVUkEKLS0tIG15YWRuOURra0Q3bXB5NkNLazlL
            cGxxZUJ5cER4cXgyUTdreGJKaDVCRWMKEZFwtNUJyJAeexSH2golUrTUdDzhMUPW
            NhXfjtTA/G8A3S9rsxHjbj/zZDvH5QtkRh12jQ4AC6G2u3+JqCeWpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T05:19:59Z"
    mac: ENC[AES256_GCM,data:Do6c9qGsuD54X0wiKmuU1xUKZeMhe9I2vbhWESC2DPwadozG27HFBAst61XBO/+07nfpdRXlb1qwfeiBmM3rx2g4qg+zSBsCDBXCOnVPdrCfjVGpKPbVk4Q1q+fIRtzaiskdKSRumavpL0gydmdAZ+74ITZWIZyjXPzJOof4juQ=,iv:wm0hm6TuZb1HFfgDe7FI+JjW5eqtJKuskYRWuopjz6w=,tag:V2gUdQtTMn8u9XLN1+cFyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
