apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:fOu6OCky4JKnon1h,iv:MWFaD5MorAdMDsYZl8jucIfMzi34VBZH+1cezJnrH8U=,tag:BsuRgtd13JKPojLNXIX6ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaG0zSzkyeisxQWx2Mkdw
            UWRZNVlWa3BreW5GYmIwWnJUU1RxVzhuK0I4Ci8za2xwZGVoZ3BrU25haDFpVE9p
            WkxyS0ZQc3dLVzlGRFIzT2FFbW9McTQKLS0tIFFRRENUWjNyVWo2R0JsajNRMW5O
            a2ZjQ0JOSllOK3JlWDVScU4vbVZNU1EKUj1m8wTvC2V6Ti2cH9pgIqcSkafU3CPR
            lSRX8jlRdhFuBQV8PxCZjKUlVsDXep4WA5OChKKl5kFzCFqZnXgZ3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:36Z"
    mac: ENC[AES256_GCM,data:+8N3XYxwdIFk3aNqju8slHLE5qxuOvqWNYDbvoIfS31SPur57U0sfYSe83usWQ3v7dblVrUOAvwPS+kj7mR/1ttQYfmupuJlBzKb+uwUEKOChtYa06vs6bZjn4Zsk5uXwFzReKQDWTXT8P/E71/CsvdpvmeKRWTvKiEjVYoefNc=,iv:BxP/KLW9axGmQJk9UbNGvKnwHSyMBBShZ5ZdEQLN5QM=,tag:Gt4A7rtScJkzh9m+in+Xyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
