apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:v3bM7QIRMFau0ITb,iv:7Qc96DAW+U7wEHBaTvfAbmS23GzvKW+3+STLya5Qg58=,tag:woxFE7cU2NQuFyZEAhe8oQ==,type:str]
    SECRET_SYNO_ADDR: ENC[AES256_GCM,data:UfqAx9pSI0UgjQ==,iv:qKGhuyA9FqQ4i/WHQA6yY9xU9fdc4J9wLzzH/Z+md70=,tag:WYGA82IFWlL6EESMLvU1gg==,type:str]
    SECRET_NFS_KUBES: ENC[AES256_GCM,data:AKF1lz2GwQ/G9zsbLiQ=,iv:ua4JdiOFrIKCQ9B4zFfdL8nzz0jiCXKv09xNWAtBdeY=,tag:6KQNgymsH1C4MyaxVyVHag==,type:str]
    SECRET_NFS_MEDIA: ENC[AES256_GCM,data:3bohaudHloebLJz4sFc=,iv:OTBqLVjSSihaOl1+a2tKrvamsKql7CPmdnMdWsPDMIQ=,tag:LAxSezD7z4CwWh3z6vCPPA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNU1ZJakUyOXd2OGx4VXlh
            YjJSNUt5TklrODlEOGw5SFM3dXFmNUlCMFNzCmVDQmUxVlI1MTUyRlIrN0o0c2sz
            RjYrdHJvaDJIV2RGY3FPQm12R2VFbkEKLS0tIEhZaERvVVNNQWhhSlJQbzMrNTBJ
            MEVCa1Z0WTJVZXp4bGdhMWRRNmRZZEUKH0PqhctBmcnAn/mcp6XPqfVSQ2CTRO89
            DGrorVjFnz4MQqPINFB9HDLCVgo63o5ciE8zcgkJFpvFsuzb+Ci/gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-08T01:47:49Z"
    mac: ENC[AES256_GCM,data:GgcBeCwsGxods7vOUZsQNSc3HyH5rhrZQZ6naMo4C+aNpz+49k/mj64siHt0SzemI4CkvGZUOK4cUhZmFLXo09RZM5mWGelCg0iXksMLjcOOLw3JfYOXh8+JWrLiMMcfuT/8cFbwJXSqITWkz9PbwLPxhrnTswvE7KU0J+Dq/5s=,iv:Jvy1PvFpHybok/eze864U495lKdp4eiFCgXtSFrJ5l8=,tag:/VmIaKBoOyioSN9KqnYfXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
