apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:kfLNZtFLxUmROH0QLRja4g1+,iv:5Kti62p18i7uttzn1Y/bJP5Q7hiZHusXYaUyJtD1Th0=,tag:qOApnBZwh0op+0O3iF/qww==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:F7FSej2iA8TDn8KF9xdv64xr7xydooChZqrWPWNKRaQWhFlh,iv:f34ydrSb47xzQGwWp7/E0Of3T8fpEvxHstteAxN6pKg=,tag:VcAZF+axBuzynbcyvG5ntg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:vRM+AUO/zAy4/SJ1+YN/cw==,iv:bC5mj5Ucb8bk5e+hWNpzO0AKyIiLkkMD63PTzuR2Tfs=,tag:ewqAuSS5o1kodm46NdE9kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL3diOG53K2F5TFBxQ1g0
            S2djeS9ncEpKWnQrNFZGZ29hQVd4dTdsV0dVCmVIbEdIc2RrOWxEVmlldUdoNkhQ
            S3Y4bXVBaXdsSUNJSmdOY2llYXNXNmsKLS0tIEJCYUR6eHJSaHpxZ3hlVmdsTUhn
            Ykc5c05PVlZEcjk3Q1ZlWkhoYTZuam8Kk7BC+kfms+a20jycuju9RWEXY5SYi0HT
            YgvhaQ69TxuocX4Qn+Q4i6oPDulctWUcpjw9a14cNj5iIHQPBEU7hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:36Z"
    mac: ENC[AES256_GCM,data:tIDAtYFkvVsQ0v/qlkgEjdrOcg0GqnuRIlA6RxRBREncWGmaz+N54uBaBADg2FnLmaCcxUgqEpLflsZsNeQ8Bo6QnFnXnOBGs7ip3WnIKnE8YrSZLzXDkUOBAe6HuD/EhAyOjl9GRm7rUi+bpUO/FykOqE7b5K4Y7DxejZ+9Qfc=,iv:koCKt4Qk8XcQtsdAyAaFc27r5L3WLw/9stE/d4yEfSQ=,tag:pPdgsod4BZoQZFvhINVyHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
