---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teslamate-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  teslamate-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: TeslaMate
        uid: TeslaMate
        type: postgres
        url: teslamate-postgres.home.svc.cluster.local:5432
        database: teslamate
        user: teslamate
        secureJsonData:
          password: "${TESLAMATE_DB_PASSWORD}"
        jsonData:
          database: teslamate
          sslmode: disable
          postgresVersion: 1700
          timescaledb: false
        isDefault: false
        editable: false
