---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: searxng
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: searxng-secret
    template:
      data:
        SEARXNG_SECRET: "{{ .secret_key }}"
  data:
    - secretKey: secret_key
      remoteRef:
        key: searxng
        property: secret_key
