---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webtop
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: webtop-secret
  dataFrom:
    - extract:
        key: webtop
