---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bambuddy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: bambuddy-secret
    template:
      data:
        mfa_encryption_key: "{{ .mfa_encryption_key }}"
  dataFrom:
    - extract:
        key: bambuddy
