---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autoscan
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: autoscan-secret
    template:
      data:
        config.yml: |
          minimum-age: 2m

          authentication:
            username: autoscan
            password: thisisashittypassword

          port: 3030

          triggers:
            sonarr:
              - name: sonarr
                priority: 1
              - name: sonarr4k
                priority: 3

            radarr:
              - name: radarr
                priority: 2
              - name: radarr4k
                priority: 4

          targets:
            plex:
              - url: http://10.0.3.2:32400
                token: "{{ .plex_token }}"
                rewrite:
                  - from: /data/media/
                    to: /data/
  dataFrom:
    - extract:
        key: autoscan
