apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:0DNyHgEhpV6yyhZNVzlfcAG+S2oNinVyDOjNAPPUeM0DR17z,iv:k4fcn3AuNeCto9EAAChYSGVVwCagIIRmiF1zhh4x5iE=,tag:LZg310B3IYqIvbPPRXZH2g==,type:str]
    credentials.json: ENC[AES256_GCM,data:NYgLIgGY6CUrldon6jtBoA9dYQZCmozMJ8gGPQy4px+V+slrXsnxs69A+4MqUnJhF/v9/TChjDBjH0Na/q7fVcsmzrksUnHZxLIn0yPjhW0xFgy0hKiSsa64394U9328RppxWNFxRnDg9lCYVywv+wMVT9v8gGlY8EdskiaZzC9xi2JOtYJUlPy9d0c7bkeFNSbiPkp+QbdqjlbDYfISGcrEWOKYaUWqWVi9/3T2xQ==,iv:VGuvwlMFkNk3J0vgF2atGGoQGav0gAvHMlKT4aANpLA=,tag:sivwVL4+SjY2HR7g+GQPwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lg6nrq3a6zdgtxgf5d9xvf7gxhl36vtvnu48ar28e8sjuunw5ejqs89ehd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScjRucXY1c0FGSlZTM2RY
            VUhsTHYrUHowdmlLeWUvZlZmcnlIZlVvOWlZCldNUDJZamRLbnJaQUgyNDRMOXJP
            bVdMRjlISS9xc2luTnhSQU9ubU4zTWcKLS0tIEZ2YzJsaHBjWDZCVjJBMVVsakZk
            OGpiY1VhN2tmTVpwdVB2VlJTb09DZXMKBEJYiIFBhJP+CpJYTMzO57mR8Uammp1R
            GtHFsQtKn6f44qtNPT+SBU6PZ2fNuNP+JFFijrlp7HF9OH3rB4mLfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-26T03:44:37Z"
    mac: ENC[AES256_GCM,data:pk/fXCaYDGhHQRuZuEZLuXak73lExu7K4fg13aQs/LvMx09deOWGgzjTTygv5zotyn5G3Q2N4qAAtZAYhjdGjB0GmeWL1yzEOwEIEZkKTiApKy/oSR+KFG7YTrXnaPT2Rc9i5+A2e7WQU9RvtxYoOsw+UKDJ/Lux7fV3hhqhrNo=,iv:Sp8kSxdUy5rZhCJb9PKdIU5pn5BPre3L+hyr63A/9mE=,tag:rLdg0XCvOXrCTHvXPHuGGQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
