---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate-grafana-vars
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: teslamate-grafana-vars
  data:
    - secretKey: TESLAMATE_DB_PASSWORD
      remoteRef:
        key: teslamate
        property: db_password
