---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepasswordSDK:
      # connectHost: https://connect.1password.com
      vault: homeops
      auth:
        serviceAccountSecretRef:
          key: token
          name: onepassword-connect-secret
          namespace: external-secrets