# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-secret
stringData:
  token: ENC[AES256_GCM,data:j2W3cV5Tv2ChzfctA9G/WPpfXaxr73vmHSSea7XXK0byVbln/aZ15Y2rDWfeBK/SKzWPJYrCY8bcK9Lr3Np9JnwGbXAroYqSRzfRP2+LuGY/8mTwVpRFjCmMcJ/5IJjUfEUeMhjtbrEOV/byuJZ485NSmsDzGUm3DFn9ahf55Nm3Go0876wNnHd3MZIBVUtjVINWwe+Enm2ulevbnv5rKBnbQtmuv8mrO4eEmahRuT7iG1psMbqI8PJmKY/dYC7PAIVVoIuEWztCExP7Et4bYRFb8gTBUI299TdpWtcRAHOWE5EljLyPfKmsMVuImYD+kuo943ie/PXLK6HJgt65anli0vij1Fz405TRPxjPw5jARgUyXoUmPdHeEKguckBWr5SkNx0zExvw+HhSwffiIDH6bqUEAVG+aHkYivt8sWhPWvZVTdyYYoM+gVqZg06zMFesu6GmzgN72BF5K0m4a37X0m66gQ/LqKe0QaUqgYruY8hzCgN6OUsYeeIdBxPxCGDh9ij9Ov4X8DTRp+3aQqsX7rdOKI3lcyIswThiCMTD+S2KOr/lKpDhagaFPMULRvGKgJTfIvt2BR0hSsLH2Ua23tarvFDoQJOT3vdcsYltxTDbHYKsMfp8PI3We1vdM2mydp4gBXGtBoTBqnv17Jlyr70J6SEk+6F143BUmsCWZX9Y6K62s/3cyOFaJTN6LNjgVOezwk+MLjya2RscuQC7kvNbGTVxlME3itZwg6LB+eS0M8PlFhdtaWRr9sUbLOovs5UsJnh+VRc+6dK3x+0+82j6yyGBRheZyfCO3Dzvrl1VxsQW3PeNSbv4BLpri06942SPPJfUPkQoE0eoRQ8lGf0/hQO+IIPwlh3HY7mVGn3Uq+EC6ysuF8qPn922IjcpEdwEl6p8M5gVX3auKtBz2uenAQzcrX83jvDyCZlE0LUamSihn2R1Q14I924WGuKO8gEJ+vDOoyb0m6sKE7Ora9oPqBFxLmgJPMwvbDc9RTBNw1L3cOj0NYcIz99W/pf8ZlLq7lqy/2ol91nTHMlb9ZCzruEta0u9NxdXh0EMAd1wcvKjxS8obfNrLGPkhOqUJyWNnYY7+C7XN/Dj+Kbq8vkDRcvhW9l6hK7W9pOugFHT,iv:udQ8qjuLkS4p+MhRXEew61jig8dQmVqKR42zLTz88ms=,tag:gmn7Q+Ns4gdCFtEi5ecv9Q==,type:str]
sops:
  age:
    - recipient: age156rapz89dnkf0vr7c9xcp5hzwp23dzm0h8uqg7vcwlrgf8agcqtq0duew5
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OXBKcmhGQno2SUJNZzdz
        WnRPZnBvSGhFemFiY0R3VkZBOU52OXM0dG5VCjFma2g4cEZuVkxaVVYwUXF6enN3
        RUFidDhGbHdHNldjdDBVUmRhWHpZSzgKLS0tIEdOSjBUa0N4aVYvRXQ4WnN2Umti
        bkR5WXpFUXBNdzBrWlIzYmxyYkc1QkEKY/K744RwKGYMmDFioMl1ICa3tSYrLUYK
        ZftOHoCoge6MBiRtKgKRYYR+OwMcekVrdIwiYkxqcD801KWbHbGasg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T21:03:45Z"
  mac: ENC[AES256_GCM,data:+x2Je6ALwZFqyD/956F2iJiJPppq66kfsSt0yFNcJpA+7we4IIaLEdHqaxd4QR/++oQJnfRqqGasn9RQMoTB5PheKn8wynnrRfqUZyZ5eqlKM+8DK9+ha7JsaxMEY9qU6THC87zvfNMNNEI1LBVcYsImjUbITk+iWUVMBBXZsgU=,iv:KZY6D0AyIZEGH6X/EqnyHdx/56ZaKOT9G2N1C1gExYM=,tag:sPWrHEJnQWOeTyjtak6k2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
