---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-alert
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-store
  target:
    name: longhorn-backup-alert-secret
    template:
      data:
        DISCORD_WEBHOOK_URL: "{{ .password }}"
  dataFrom:
    - extract:
        key: discord-webhook-jarvis
