---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-store
spec:
  provider:
    onepassword:
      # Connect to 1Password Connect Server API
      connectHost: http://onepassword-connect.security.svc.cluster.local:8080

      # Vaults accessible by this ClusterSecretStore
      # Vaults are searched in order - first match wins
      vaults:
        homeops: 1  # Priority 1 - searched first

      # Authentication via access token
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secret
            namespace: security
            key: token
