---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: cluster-1p-secrets
spec:
  # Sync to all namespaces managed by cluster-apps Flux Kustomization
  namespaceSelector:
    matchLabels:
      kustomize.toolkit.fluxcd.io/name: cluster-apps
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-store
    target:
      name: cluster-1p-secrets
      creationPolicy: Owner
    dataFrom:
      - extract:
          key: cluster-1p-secrets
